### PR TITLE
Add network interface information collection

### PR DESCRIPTION
**Pull request by ByteOtter**
# What does this PR change?

TODO:

- [x] Deconstruct `NetworkInterface` Objects and pass all values to a custom struct for easier handling
- [x] Add Check to differentiate between physical or virtual network interfaces
- [x] Create custom `InvalidNetworkInterface` exception for error handling
- [x] Implement proper error handling

Tick the applicable box:
- [x] Add new feature
- [ ] Security changes
- [ ] Tests
- [ ] Documentation changed
<br/>

- [ ] General Maintenance

## Links

Fixes: #4 

- [x] DONE

## Documentation

- Documented with DocStrings
<br/>

- [x] DONE

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@ByteOtter It is weird that the Push check fails and the Pull Request succeeds. In theory, it should use the same config and commit. In any case, the check doesn't need to be executed twice if my understanding is correct.

Other than that I would really like you to start adding tests. I know you do manual tests and I am sure that they will cover most cases but this project should start receiving automated tests sooner than later. IMHO integration tests with the GitHub runners are fine for me.

**Comment by ByteOtter** [comment]
> @ByteOtter It is weird that the Push check fails and the Pull Request succeeds. In theory, it should use the same config and commit. In any case, the check doesn't need to be executed twice if my understanding is correct.
> 
> Other than that I would really like you to start adding tests. I know you do manual tests and I am sure that they will cover most cases but this project should start receiving automated tests sooner than later. IMHO integration tests with the GitHub runners are fine for me.

Hey, thanks for your feedback.

I need to redo the status checks and my pre-commit hooks anyway so as long as one of the two succeeds and I manually format and clippy my code it is fine for now.

Regarding tests: You are absolutely right. I am already tracking this and I am currently reading about automated unit testing in Rust.
As the main functionality for the collection feature itself should be completed now I will add tests for the`network collector` in this PR and ones for the `system collector` in a seperate PR after that.

For now though I am tracking an persumed issue with the logic that differentiates a physical network interface from a virtual one. 👀

(This message has been send from my phone please keep all typos you happen to find. ✌🏼)

**Comment by SchoolGuy** [comment]
@ByteOtter Sounds more than reasonable. Please proceed this way. :)

**Review by SchoolGuy — APPROVED** [review]
LGTM

**Pull request merged**
